# Music to Book

## Bollywood Songs Dataset

### Step 1: Training the model for music genre classification

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [ ]:
!cd '/content/drive/MyDrive/IR_Project_Music/Songs'

In [ ]:
Bolly_rap = pd.read_csv("/content/drive/MyDrive/IR_Project_Music/Songs/Bollywood_Rap_features.csv")

In [ ]:
Bolly_rap.shape

(100, 14)

In [ ]:
Bolly_rap.head()

,Unnamed: 0,Song_Name,onset_strength,chroma_stft,chroma_cqt,chroma_cens,melspectrogram,mfcc,spectral_centroid,spectral_bandwidth,spectral_contrast,spectral_rolloff,tonnetz,zero_crossing_rate
0,0,Bollywood_Rap/Bohemia - Dada.opus,1.359504,0.504378,0.431088,0.238247,12.234897,0.155766,3336.742281,3691.313529,19.326488,7111.706785,-0.029229,0.063615
1,1,Bollywood_Rap/Bohemia - Beparwah.opus,1.367846,0.481887,0.527467,0.255920,5.386636,1.173165,3813.465951,3903.036168,20.049207,8436.634644,0.027319,0.080023
2,2,Bollywood_Rap/Bohemia - Desi Put Javaan.opus,1.522658,0.614667,0.415879,0.241032,22.373873,4.658426,2062.671542,3053.880091,18.504100,4707.484604,-0.016368,0.024910
3,3,Bollywood_Rap/Bohemia - Dil Acapella.opus,1.428467,0.593779,0.524480,0.263806,17.920794,4.753779,2267.229849,3129.322550,20.090888,5376.694052,0.017713,0.041050
4,4,Bollywood_Rap/Bohemia - Aja Ni Aja.opus,1.541603,0.659266,0.580653,0.260237,22.393740,6.887264,4515.528428,4360.305689,17.931442,9524.892741,0.005748,0.078542

In [ ]:
Bolly_rap['labels'] = pd.Series([0 for x in range(len(Bolly_rap.index))], index=Bolly_rap.index)

In [ ]:
Bolly_rap.shape

(100, 15)

In [ ]:
Ghazal = pd.read_csv("/content/drive/MyDrive/IR_Project_Music/Songs/Ghazal_features.csv")
Ghazal['labels'] = pd.Series([1 for x in range(len(Ghazal.index))], index=Ghazal.index)

Garhwali = pd.read_csv("/content/drive/MyDrive/IR_Project_Music/Songs/Garhwali_features.csv")
Garhwali['labels'] = pd.Series([2 for x in range(len(Garhwali.index))], index=Garhwali.index)

bhajan = pd.read_csv("/content/drive/MyDrive/IR_Project_Music/Songs/bhajan_features.csv")
bhajan['labels'] = pd.Series([3 for x in range(len(bhajan.index))], index=bhajan.index)

bolly_romantic = pd.read_csv("/content/drive/MyDrive/IR_Project_Music/Songs/Bollywood_Romantic_features.csv")
bolly_romantic['labels'] = pd.Series([4 for x in range(len(bolly_romantic.index))], index=bolly_romantic.index)

sufi = pd.read_csv("/content/drive/MyDrive/IR_Project_Music/Songs/sufi_features.csv")
sufi['labels'] = pd.Series([5 for x in range(len(sufi.index))], index=sufi.index)

bhojpuri = pd.read_csv("/content/drive/MyDrive/IR_Project_Music/Songs/bhojpuri_features.csv")
bhojpuri['labels'] = pd.Series([6 for x in range(len(bhojpuri.index))], index=bhojpuri.index)

In [ ]:
frame = pd.concat([Bolly_rap, Ghazal, Garhwali, bhajan, bolly_romantic, sufi, bhojpuri], ignore_index=True)
frame.head()

,Unnamed: 0,Song_Name,onset_strength,chroma_stft,chroma_cqt,chroma_cens,melspectrogram,mfcc,spectral_centroid,spectral_bandwidth,spectral_contrast,spectral_rolloff,tonnetz,zero_crossing_rate,labels
0,0,Bollywood_Rap/Bohemia - Dada.opus,1.359504,0.504378,0.431088,0.238247,12.234897,0.155766,3336.742281,3691.313529,19.326488,7111.706785,-0.029229,0.063615,0
1,1,Bollywood_Rap/Bohemia - Beparwah.opus,1.367846,0.481887,0.527467,0.255920,5.386636,1.173165,3813.465951,3903.036168,20.049207,8436.634644,0.027319,0.080023,0
2,2,Bollywood_Rap/Bohemia - Desi Put Javaan.opus,1.522658,0.614667,0.415879,0.241032,22.373873,4.658426,2062.671542,3053.880091,18.504100,4707.484604,-0.016368,0.024910,0
3,3,Bollywood_Rap/Bohemia - Dil Acapella.opus,1.428467,0.593779,0.524480,0.263806,17.920794,4.753779,2267.229849,3129.322550,20.090888,5376.694052,0.017713,0.041050,0
4,4,Bollywood_Rap/Bohemia - Aja Ni Aja.opus,1.541603,0.659266,0.580653,0.260237,22.393740,6.887264,4515.528428,4360.305689,17.931442,9524.892741,0.005748,0.078542,0

In [ ]:
final = frame.drop("Unnamed: 0", axis=1)
final.to_csv("all_features.csv")

In [ ]:
final.head()

,Song_Name,onset_strength,chroma_stft,chroma_cqt,chroma_cens,melspectrogram,mfcc,spectral_centroid,spectral_bandwidth,spectral_contrast,spectral_rolloff,tonnetz,zero_crossing_rate,labels
0,Bollywood_Rap/Bohemia - Dada.opus,1.359504,0.504378,0.431088,0.238247,12.234897,0.155766,3336.742281,3691.313529,19.326488,7111.706785,-0.029229,0.063615,0
1,Bollywood_Rap/Bohemia - Beparwah.opus,1.367846,0.481887,0.527467,0.255920,5.386636,1.173165,3813.465951,3903.036168,20.049207,8436.634644,0.027319,0.080023,0
2,Bollywood_Rap/Bohemia - Desi Put Javaan.opus,1.522658,0.614667,0.415879,0.241032,22.373873,4.658426,2062.671542,3053.880091,18.504100,4707.484604,-0.016368,0.024910,0
3,Bollywood_Rap/Bohemia - Dil Acapella.opus,1.428467,0.593779,0.524480,0.263806,17.920794,4.753779,2267.229849,3129.322550,20.090888,5376.694052,0.017713,0.041050,0
4,Bollywood_Rap/Bohemia - Aja Ni Aja.opus,1.541603,0.659266,0.580653,0.260237,22.393740,6.887264,4515.528428,4360.305689,17.931442,9524.892741,0.005748,0.078542,0

In [ ]:
X = final.drop(["labels", "Song_Name"], axis=1)
y = final["labels"]

In [ ]:
final.shape

(594, 14)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
X_test

,onset_strength,chroma_stft,chroma_cqt,chroma_cens,melspectrogram,mfcc,spectral_centroid,spectral_bandwidth,spectral_contrast,spectral_rolloff,tonnetz,zero_crossing_rate
30,1.354720,0.609120,0.373124,0.216735,8.382829,1.581207,2500.902781,3308.551692,19.132942,5651.499276,0.044581,0.034380
299,1.502448,0.377903,0.452693,0.247739,9.228559,0.088470,2789.418964,2856.185283,21.362462,5346.094627,0.006380,0.076902
177,1.234227,0.347149,0.383848,0.224788,1.773748,-3.952408,1991.396384,2381.894970,22.001858,3614.533430,-0.012995,0.048412
204,1.438079,0.357932,0.511036,0.257713,5.892732,1.465694,2999.769963,3396.540257,21.445034,6605.602423,-0.008132,0.060593
354,1.227234,0.395746,0.382983,0.224339,20.534378,3.617873,1909.869175,2729.586489,20.517566,3969.137539,0.028177,0.032461
...,...,...,...,...,...,...,...,...,...,...,...,...
580,1.781345,0.436791,0.654907,0.277945,23.136932,6.739148,5376.722796,5083.763575,18.828939,11243.396914,0.016109,0.104739
228,1.446344,0.344111,0.477638,0.250160,9.170692,2.448629,2335.858281,3057.056229,21.375140,4714.088703,-0.008496,0.045999
84,1.326330,0.397440,0.375701,0.218782,18.590418,1.758704,2303.929357,2943.672409,20.205525,4930.952288,-0.041075,0.042215
140,1.264677,0.295499,0.381218,0.224301,4.388995,-3.010536,1723.986316,2564.079449,20.977371,3207.384785,0.028411,0.031142
394,1.470279,0.403312,0.404667,0.236443,9.217032,2.723054,1715.932522,2145.028276,21.777369,3725.538072,-0.012516,0.035500

In [ ]:
import lightgbm as lgb
clf = lgb.LGBMClassifier(boosting_type='gbdt', learning_rate=0.2, min_child_samples=20)
clf.fit(X_train, y_train)

LGBMClassifier(learning_rate=0.2)

In [ ]:
y_pred=clf.predict(X_test)
print(y_pred)
print(y_test)

[0 6 1 2 4 2 4 6 0 2 1 0 4 4 5 2 4 5 0 2 0 5 0 4 2 6 5 2 5 0 6 6 0 2 1 5 4
 5 1 3 2 3 0 6 4 4 4 1 6 3 2 6 4 1 0 1 6 0 4 0 6 6 0 4 2 6 4 6 6 3 3 4 4 0
 0 0 5 6 2 6 4 4 0 5 6 2 0 0 2 0 0 6 1 6 0 5 5 2 1 5 1 5 1 0 2 3 6 6 1 0 2
 1 1 4 6 2 0 1 4]
30     0
299    3
177    1
204    2
354    4
      ..
580    6
228    2
84     0
140    1
394    4
Name: labels, Length: 119, dtype: int64

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
accuracy=accuracy_score(y_pred, y_test)
print('LightGBM Model accuracy score: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))

LightGBM Model accuracy score: 0.6471

### Testing the model for new songs

In [ ]:
pip freeze | grep librosa

librosa==0.10.0.post2

In [ ]:
pip install librosa==0.8.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting librosa==0.8.1
  Downloading librosa-0.8.1-py3-none-any.whl (203 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.8/203.8 kB 5.3 MB/s eta 0:00:00
Collecting resampy>=0.2.2
  Downloading resampy-0.4.2-py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 41.6 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (1.2.2)
Requirement already satisfied: audioread>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (3.0.0)
Requirement already satisfied: decorator>=3.0.0 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (4.4.2)
Requirement already satisfied: numba>=0.43.0 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (0.56.4)
Requirement already satisfied: pooch>=1.0 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (1.6.0)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (1.2.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (1.10.1)
Requirement already satisfied: soundfile>=0.10.2 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (0.12.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (23.1)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.9/dist-packages (from librosa==0.8.1) (1.22.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (from numba>=0.43.0->librosa==0.8.1) (67.6.1)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /usr/local/lib/python3.9/dist-packages (from numba>=0.43.0->librosa==0.8.1) (0.39.1)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.9/dist-packages (from pooch>=1.0->librosa==0.8.1) (2.27.1)
Requirement already satisfied: appdirs>=1.3.0 in /usr/local/lib/python3.9/dist-packages (from pooch>=1.0->librosa==0.8.1) (1.4.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa==0.8.1) (3.1.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.9/dist-packages (from soundfile>=0.10.2->librosa==0.8.1) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.0->soundfile>=0.10.2->librosa==0.8.1) (2.21)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.1) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.1) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.1) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.19.0->pooch>=1.0->librosa==0.8.1) (1.26.15)
Installing collected packages: resampy, librosa
  Attempting uninstall: librosa
    Found existing installation: librosa 0.10.0.post2
    Uninstalling librosa-0.10.0.post2:
      Successfully uninstalled librosa-0.10.0.post2
Successfully installed librosa-0.8.1 resampy-0.4.2

In [ ]:
import librosa
from librosa import feature

In [ ]:
fn_list_i = [ 
    librosa.onset.onset_strength,            
    feature.chroma_stft,                       
    feature.chroma_cqt,
    feature.chroma_cens,
    feature.melspectrogram,
    feature.mfcc,
    feature.spectral_centroid,
    feature.spectral_bandwidth,
    feature.spectral_contrast,
    feature.spectral_rolloff,
    feature.tonnetz
]

fn_list_ii = [
    feature.zero_crossing_rate
]

def get_feature_vector(y,sr): 
   feat_vect_i = [ np.mean(funct(y, sr)) for funct in fn_list_i]
   feat_vect_ii = [ np.mean(funct(y)) for funct in fn_list_ii] 
   feature_vector = feat_vect_i + feat_vect_ii 
   return feature_vector

In [ ]:
cd '/content/drive/MyDrive/IR_Project_Music/OPUS test files'

/content/drive/.shortcut-targets-by-id/16J3C8U4VbHN5OnAeYfjDjwNggiLzZx0K/OPUS test files

In [ ]:
ls

'Abhijeet Srivastava - Chashni (From Bharat).opus'
'Abida Parveen - Aaqa - Coke Studio Season 9.opus'
'Akhil - Duniyaa.opus'
 Apna-Time-Aayega-Gully-Boy-Ranveer-Singh-_-Alia-Bhatt-DIVINE-Dub-Sharma-Zoya-Akhtar.opus
 BAARISHEIN-_Studio_-Anuv-Jain.opus
'Bohemia - Lak Da Hulara.opus'
'Guru Randhawa - Lahore - Remix(Remix By Dj Shadow Dubai).opus'
 Kehna-Hi-Kya-_-Bombay-_-Sanah-Moidutty.opus
 Matkar-Maya-Ko-Ahankar-_Audio_-By-Neeraj-Arya_s-Kabir-Cafe-From-Album-Panchrang.opus
 Mero-Mann-Lagyo-Vrindavan-Mein-_-Krishna-Bhajan-Maanya-Arora-_-Latest-Bhajan-2023.opus
 PATWARI-2-_-New-Garhwali-Song-2023-_-Rohit-Chauhan-_-Raj-Tiger-New-Gadwali-Song-2023.opus
 Pawan-Singh-_-अंखिया-मिलाओ-_-Palak-Muchhal-_-Ankhiya-Milao-_-Madhu-Sharma-_-New-Bhojpuri-Song-2022.opus
 RadhaKrishn-_-Samay-Samjhayega-_-Surya-Raj-Kamal-_.opus
 Ranjha-Lyric-Video-Shershaah-Sid.opus
'SalimSulaiman - Saaiyaan.opus'
'Sidhu Moose Wala - Boss.opus'
 Soulful-Ghazal-Hariharan-Live-at.opus
 test_file_features.csv

In [ ]:
from glob import glob

In [ ]:
test_files = glob('/content/drive/MyDrive/IR_Project_Music/OPUS test files/*.opus')
test_files

['/content/drive/MyDrive/IR_Project_Music/OPUS test files/BAARISHEIN-_Studio_-Anuv-Jain.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Kehna-Hi-Kya-_-Bombay-_-Sanah-Moidutty.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Matkar-Maya-Ko-Ahankar-_Audio_-By-Neeraj-Arya_s-Kabir-Cafe-From-Album-Panchrang.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Mero-Mann-Lagyo-Vrindavan-Mein-_-Krishna-Bhajan-Maanya-Arora-_-Latest-Bhajan-2023.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/PATWARI-2-_-New-Garhwali-Song-2023-_-Rohit-Chauhan-_-Raj-Tiger-New-Gadwali-Song-2023.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Pawan-Singh-_-अंखिया-मिलाओ-_-Palak-Muchhal-_-Ankhiya-Milao-_-Madhu-Sharma-_-New-Bhojpuri-Song-2022.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/RadhaKrishn-_-Samay-Samjhayega-_-Surya-Raj-Kamal-_.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Ranjha-Lyric-Video-Shershaah-Sid.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Soulful-Ghazal-Hariharan-Live-at.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Abhijeet Srivastava - Chashni (From Bharat).opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Abida Parveen - Aaqa - Coke Studio Season 9.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Akhil - Duniyaa.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Bohemia - Lak Da Hulara.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Guru Randhawa - Lahore - Remix(Remix By Dj Shadow Dubai).opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/SalimSulaiman - Saaiyaan.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Sidhu Moose Wala - Boss.opus',
 '/content/drive/MyDrive/IR_Project_Music/OPUS test files/Apna-Time-Aayega-Gully-Boy-Ranveer-Singh-_-Alia-Bhatt-DIVINE-Dub-Sharma-Zoya-Akhtar.opus']

In [ ]:
columns = ["Song_Name", "onset_strength", "chroma_stft", "chroma_cqt", "chroma_cens", "melspectrogram", "mfcc",	
           "spectral_centroid" ,"spectral_bandwidth", "spectral_contrast", "spectral_rolloff",	"tonnetz", "zero_crossing_rate"]

In [ ]:
song_features = []
for file in test_files:
  '''
  y is the time series array of the audio file, a 1D np.ndarray
  sr is the sampling rate, a number
  '''  
  y,sr = librosa.load(file,sr=None)   
  feature_vector = get_feature_vector(y, sr)
  song_features.append([file] + feature_vector)
df = pd.DataFrame(song_features, columns=columns)
file_name = 'test_file_features.csv'
df.to_csv(file_name)

In [32]:
test = pd.read_csv("/content/drive/MyDrive/IR_Project_Music/OPUS test files/test_file_features.csv")
test.head()

,Unnamed: 0,Song_Name,onset_strength,chroma_stft,chroma_cqt,chroma_cens,melspectrogram,mfcc,spectral_centroid,spectral_bandwidth,spectral_contrast,spectral_rolloff,tonnetz,zero_crossing_rate
0,0,/content/drive/MyDrive/IR_Project_Music/OPUS t...,0.988178,0.455188,0.251505,0.173661,12.358196,-3.426518,1670.126207,2446.729329,23.590304,3168.877797,0.015203,0.030004
1,1,/content/drive/MyDrive/IR_Project_Music/OPUS t...,1.127582,0.348878,0.296707,0.189053,3.994343,-4.107227,2191.983252,2917.319130,22.426798,4796.555479,-0.053757,0.036979
2,2,/content/drive/MyDrive/IR_Project_Music/OPUS t...,1.349172,0.428706,0.386898,0.227331,10.927579,4.067034,2404.951197,3437.479894,23.393237,5290.902840,-0.015973,0.037833
3,3,/content/drive/MyDrive/IR_Project_Music/OPUS t...,1.537121,0.357567,0.422371,0.235730,9.671809,2.293517,3214.333699,3906.905808,22.922920,7353.758893,-0.013865,0.058525
4,4,/content/drive/MyDrive/IR_Project_Music/OPUS t...,1.525814,0.400754,0.550733,0.258779,8.306067,-2.599203,3286.273804,3377.062323,21.798184,6917.936758,-0.012998,0.067830

In [33]:
X_test = test.drop(['Unnamed: 0', 'Song_Name'], axis = 1)
X_test.head()

,onset_strength,chroma_stft,chroma_cqt,chroma_cens,melspectrogram,mfcc,spectral_centroid,spectral_bandwidth,spectral_contrast,spectral_rolloff,tonnetz,zero_crossing_rate
0,0.988178,0.455188,0.251505,0.173661,12.358196,-3.426518,1670.126207,2446.729329,23.590304,3168.877797,0.015203,0.030004
1,1.127582,0.348878,0.296707,0.189053,3.994343,-4.107227,2191.983252,2917.319130,22.426798,4796.555479,-0.053757,0.036979
2,1.349172,0.428706,0.386898,0.227331,10.927579,4.067034,2404.951197,3437.479894,23.393237,5290.902840,-0.015973,0.037833
3,1.537121,0.357567,0.422371,0.235730,9.671809,2.293517,3214.333699,3906.905808,22.922920,7353.758893,-0.013865,0.058525
4,1.525814,0.400754,0.550733,0.258779,8.306067,-2.599203,3286.273804,3377.062323,21.798184,6917.936758,-0.012998,0.067830

In [34]:
y_pred = clf.predict(X_test)

In [35]:
for i in range(len(test_files)):
  print(test_files[i], " : ", y_pred[i])

/content/drive/MyDrive/IR_Project_Music/OPUS test files/BAARISHEIN-_Studio_-Anuv-Jain.opus  :  4
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Kehna-Hi-Kya-_-Bombay-_-Sanah-Moidutty.opus  :  1
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Matkar-Maya-Ko-Ahankar-_Audio_-By-Neeraj-Arya_s-Kabir-Cafe-From-Album-Panchrang.opus  :  5
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Mero-Mann-Lagyo-Vrindavan-Mein-_-Krishna-Bhajan-Maanya-Arora-_-Latest-Bhajan-2023.opus  :  2
/content/drive/MyDrive/IR_Project_Music/OPUS test files/PATWARI-2-_-New-Garhwali-Song-2023-_-Rohit-Chauhan-_-Raj-Tiger-New-Gadwali-Song-2023.opus  :  2
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Pawan-Singh-_-अंखिया-मिलाओ-_-Palak-Muchhal-_-Ankhiya-Milao-_-Madhu-Sharma-_-New-Bhojpuri-Song-2022.opus  :  2
/content/drive/MyDrive/IR_Project_Music/OPUS test files/RadhaKrishn-_-Samay-Samjhayega-_-Surya-Raj-Kamal-_.opus  :  1
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Ranjha-Lyric-Video-Shershaah-Sid.opus  :  4
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Soulful-Ghazal-Hariharan-Live-at.opus  :  1
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Abhijeet Srivastava - Chashni (From Bharat).opus  :  4
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Abida Parveen - Aaqa - Coke Studio Season 9.opus  :  5
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Akhil - Duniyaa.opus  :  4
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Bohemia - Lak Da Hulara.opus  :  0
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Guru Randhawa - Lahore - Remix(Remix By Dj Shadow Dubai).opus  :  0
/content/drive/MyDrive/IR_Project_Music/OPUS test files/SalimSulaiman - Saaiyaan.opus  :  4
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Sidhu Moose Wala - Boss.opus  :  0
/content/drive/MyDrive/IR_Project_Music/OPUS test files/Apna-Time-Aayega-Gully-Boy-Ranveer-Singh-_-Alia-Bhatt-DIVINE-Dub-Sharma-Zoya-Akhtar.opus  :  0

### Step 3: Mapping from Music to Book Genre

In [37]:
from gensim.models import KeyedVectors
# Load vectors directly from the file
model = KeyedVectors.load_word2vec_format('/content/drive/MyDrive/GoogleNews-vectors-negative300.bin.gz', binary=True)

In [38]:
# Calculate the mean vector for each book genre
genre_vectors = []
#book_genres = ['bhajan']

music_list = ['rap', 'ghazal', 'folk', 'bhajan', 'romantic', 'sufi']

#main_genres = ['Fiction','Comedy','Adventure', 'Non-fiction', 'Romance', 'Mystery', 'Science Fiction', 'Fantasy', 'Horror', 'Historical Fiction', 'Young Adult', 'Spirituality']
main_genres = ['History', 'Poetry', 'Autobiography', 'Romance','Biography', 'Literary', 'Spirituality', 'Western fiction', 'Comedy', 'Adventure',
               'Dark', 'Sociology', 'Comic', 'Anthology', 'Drama', 'Thriller', 'Action',  'Conspiracy', 'Catastrophic', 
               'Young adult','Fantasy', 'Travel', 'Science', 'Speculative', 'Horror', 'Mystery', 'Non fiction']

for genre in music_list:
    genre = genre.replace('-', ' ')
    genre = genre.replace('\'', ' ')
    #genre = genre.replace('edisonade', 'inventor')
    tokens = genre.lower().split()
    vector = sum(model[token] for token in tokens) / len(tokens)
    genre_vectors.append(vector)



main_genre_vectors = []
for genre in main_genres:
    genre = genre.replace('-', ' ')
    tokens = genre.lower().split()
    vector = sum(model[token] for token in tokens) / len(tokens)
    main_genre_vectors.append(vector)

In [39]:
import pandas as pd
genre_df = pd.DataFrame()
genre_df['genre'] = music_list

In [40]:
len(music_list)

6

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

# similarity_list = []
# map_j_list = []
u_genre_list = []
for j in range(0,6):
  similarity_list = []
  map_j_list = []
  for i in range(len(main_genre_vectors)):
    similarity = cosine_similarity([genre_vectors[j]], [main_genre_vectors[i]])[0][0]
    similarity_list.append(similarity)
    map_j_list.append(i)
  #idx = similarity_list.index(sorted(similarity_list)[-1])
  top5_ls = [similarity_list.index(x) for x in sorted(similarity_list)[-5:]]
  temp = []
  for k in top5_ls:
    temp.append(main_genres[k])
  u_genre_list.append([temp])  
  # print(f"Cosine similarity between '{bhajan}' and '{spirituality}': {similarity:.2f}")
  # print(main_genres[i])
  # print(u_genre_list[j])


genre_df['m-genre'] = u_genre_list

In [42]:
genre_df

      genre                                            m-genre
0       rap  [[Sociology, Young adult, Comic, Comedy, Poetry]]
1    ghazal  [[Western fiction, Romance, Anthology, Literar...
2      folk  [[Comedy, Literary, Western fiction, Spiritual...
3    bhajan  [[Comic, Comedy, Literary, Spirituality, Poetry]]
4  romantic  [[Western fiction, Spirituality, Comedy, Adven...
5      sufi  [[Romance, Western fiction, Literary, Spiritua...

In [43]:
dct = {}
dct.update(genre_df['m-genre'])
dct

{0: [['Sociology', 'Young adult', 'Comic', 'Comedy', 'Poetry']],
 1: [['Western fiction', 'Romance', 'Anthology', 'Literary', 'Poetry']],
 2: [['Comedy', 'Literary', 'Western fiction', 'Spirituality', 'Poetry']],
 3: [['Comic', 'Comedy', 'Literary', 'Spirituality', 'Poetry']],
 4: [['Western fiction', 'Spirituality', 'Comedy', 'Adventure', 'Romance']],
 5: [['Romance', 'Western fiction', 'Literary', 'Spirituality', 'Poetry']]}

In [44]:
dct[6] = [['Comedy', 'Literary', 'Western fiction', 'Spirituality', 'Poetry']]
dct

{0: [['Sociology', 'Young adult', 'Comic', 'Comedy', 'Poetry']],
 1: [['Western fiction', 'Romance', 'Anthology', 'Literary', 'Poetry']],
 2: [['Comedy', 'Literary', 'Western fiction', 'Spirituality', 'Poetry']],
 3: [['Comic', 'Comedy', 'Literary', 'Spirituality', 'Poetry']],
 4: [['Western fiction', 'Spirituality', 'Comedy', 'Adventure', 'Romance']],
 5: [['Romance', 'Western fiction', 'Literary', 'Spirituality', 'Poetry']],
 6: [['Comedy', 'Literary', 'Western fiction', 'Spirituality', 'Poetry']]}

### Step 4: Processing Book Dataset

In [ ]:
import csv

Importing dataset

In [ ]:
l = []

with open("/content/drive/MyDrive/booksummaries.txt", 'r', encoding="utf8") as file:
    r = csv.reader(file, dialect='excel-tab')
    for row in r:
        l.append(row)

Identifying components of the book from the obtained list and storing the same in a dataframe

In [ ]:
Id = []
Name = []
Description = []
Genre = []

In [ ]:
for i in l:
    Id.append(i[0])
    Name.append(i[2])
    Genre.append(i[5])
    Description.append(i[6])

df = pd.DataFrame({'id': Id, 'name': Name, 'description': Description,
                       'genre': Genre})

In [ ]:
df.head()

,id,name,description,genre
0,620,Animal Farm,"Old Major, the old boar on the Manor Farm, ca...","{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":..."
1,843,A Clockwork Orange,"Alex, a teenager living in near-future Englan...","{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N..."
2,986,The Plague,The text of The Plague is divided into five p...,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi..."
3,1756,An Enquiry Concerning Human Understanding,The argument of the Enquiry proceeds by a ser...,
4,2080,A Fire Upon the Deep,The novel posits that space around the Milky ...,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90..."

In [ ]:
df.tail()

,id,name,description,genre
16554,36934824,Under Wildwood,"Prue McKeel, having rescued her brother from ...",
16555,37054020,Transfer of Power,The reader first meets Rapp while he is doing...,"{""/m/01jfsb"": ""Thriller"", ""/m/02xlf"": ""Fiction""}"
16556,37122323,Decoded,The book follows very rough chronological ord...,"{""/m/0xdf"": ""Autobiography""}"
16557,37132319,America Again: Re-becoming The Greatness We Ne...,Colbert addresses topics including Wall Stree...,
16558,37159503,Poor Folk,Makar Devushkin and Varvara Dobroselova are s...,"{""/m/02ql9"": ""Epistolary novel"", ""/m/014dfn"": ..."

In [ ]:
df.dtypes

id             object
name           object
description    object
genre          object
dtype: object

In [ ]:
df['id'] = df['id'].astype('int')

Dropping rows with empty genre

In [ ]:
df.drop(df[df['genre']==''].index, inplace=True)
df[df['genre']=='']

Empty DataFrame
Columns: [id, name, description, genre]
Index: []

In [ ]:
df.tail()

,id,name,description,genre
16549,36372465,The Third Lynx,The story starts with former government agent...,"{""/m/06n90"": ""Science Fiction""}"
16551,36534061,Remote Control,The series follows the character of Nick Ston...,"{""/m/01jfsb"": ""Thriller"", ""/m/02xlf"": ""Fiction..."
16555,37054020,Transfer of Power,The reader first meets Rapp while he is doing...,"{""/m/01jfsb"": ""Thriller"", ""/m/02xlf"": ""Fiction""}"
16556,37122323,Decoded,The book follows very rough chronological ord...,"{""/m/0xdf"": ""Autobiography""}"
16558,37159503,Poor Folk,Makar Devushkin and Varvara Dobroselova are s...,"{""/m/02ql9"": ""Epistolary novel"", ""/m/014dfn"": ..."

In [ ]:
print(list(np.where(df['name']=='The Chinese Gold Murders')))
df.iloc[7240]

[array([7240])]

id                                                       8683518
name                                    The Chinese Gold Murders
description     Judge Dee is a recently appointed magistrate ...
genre          {"/m/02n4kr": "Mystery", "/m/028v3": "Detectiv...
Name: 8639, dtype: object

Converting json format of genre to list

In [ ]:
import json as jsc

In [ ]:
jsc.loads(df['genre'][0]).values()

dict_values(['Roman à clef', 'Satire', "Children's literature", 'Speculative fiction', 'Fiction'])

In [ ]:
l=[]
for i in df['genre']:
    l.append(list(jsc.loads(i).values()))

In [ ]:
df['u-genre'] = l

In [ ]:
setOfgenre = sum(l,[])
setOfgenre = set(setOfgenre)

In [ ]:
len(setOfgenre)

227

Preprocessing description text

In [ ]:
import re

In [ ]:
def updateDescription(s):
    s = re.sub("\'", "", s)
    s = re.sub("[^a-zA-Z]"," ",s)
    s = ' '.join(s.split())
    s = s.lower()
    return s

In [ ]:
df['u-description'] = df['description'].apply(lambda x: updateDescription(x))

In [ ]:
df.head()

,id,name,description,genre,u-genre,u-description
0,620,Animal Farm,"Old Major, the old boar on the Manor Farm, ca...","{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","[Roman à clef, Satire, Children's literature, ...",old major the old boar on the manor farm calls...
1,843,A Clockwork Orange,"Alex, a teenager living in near-future Englan...","{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","[Science Fiction, Novella, Speculative fiction...",alex a teenager living in near future england ...
2,986,The Plague,The text of The Plague is divided into five p...,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...","[Existentialism, Fiction, Absurdist fiction, N...",the text of the plague is divided into five pa...
4,2080,A Fire Upon the Deep,The novel posits that space around the Milky ...,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...","[Hard science fiction, Science Fiction, Specul...",the novel posits that space around the milky w...
5,2152,All Quiet on the Western Front,"The book tells the story of Paul Bäumer, a Ge...","{""/m/098tmk"": ""War novel"", ""/m/016lj8"": ""Roman...","[War novel, Roman à clef]",the book tells the story of paul b umer a germ...

In [ ]:
df=df.drop(['genre', 'description'], axis=1)

In [ ]:
df.head()

,id,name,u-genre,u-description
0,620,Animal Farm,"[Roman à clef, Satire, Children's literature, ...",old major the old boar on the manor farm calls...
1,843,A Clockwork Orange,"[Science Fiction, Novella, Speculative fiction...",alex a teenager living in near future england ...
2,986,The Plague,"[Existentialism, Fiction, Absurdist fiction, N...",the text of the plague is divided into five pa...
4,2080,A Fire Upon the Deep,"[Hard science fiction, Science Fiction, Specul...",the novel posits that space around the milky w...
5,2152,All Quiet on the Western Front,"[War novel, Roman à clef]",the book tells the story of paul b umer a germ...

In [ ]:
df.rename(columns = {'u-genre':'genre'}, inplace = True)

In [ ]:
df.rename(columns = {'u-description':'description'}, inplace = True)

In [ ]:
df.head()

,id,name,genre,description
0,620,Animal Farm,"[Roman à clef, Satire, Children's literature, ...",old major the old boar on the manor farm calls...
1,843,A Clockwork Orange,"[Science Fiction, Novella, Speculative fiction...",alex a teenager living in near future england ...
2,986,The Plague,"[Existentialism, Fiction, Absurdist fiction, N...",the text of the plague is divided into five pa...
4,2080,A Fire Upon the Deep,"[Hard science fiction, Science Fiction, Specul...",the novel posits that space around the milky w...
5,2152,All Quiet on the Western Front,"[War novel, Roman à clef]",the book tells the story of paul b umer a germ...

In [ ]:
df.dtypes

id              int64
name           object
genre          object
description    object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12841 entries, 0 to 16558
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           12841 non-null  int64
 1   name         12841 non-null  object
 2   genre        12841 non-null  object
 3   description  12841 non-null  object
dtypes: int64(1), object(3)
memory usage: 1017.6+ KB

In [ ]:
df.shape

(12841, 4)

In [ ]:
df.describe()

                 id
count  1.284100e+04
mean   9.986379e+06
std    9.032047e+06
min    6.200000e+02
25%    2.626115e+06
50%    6.877746e+06
75%    1.557749e+07
max    3.715950e+07

In [ ]:
import nltk
from nltk.corpus import stopwords 
nltk.download('stopwords')
nltk.download('words')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
from nltk.tokenize import word_tokenize

Removing stopwords from the description

In [ ]:
def preprocess_SW(desc):
    setSW = set(stopwords.words('english'))
    tokens = word_tokenize(desc)
    newDesc = [x for x in tokens if not x.lower() in setSW]
    return ' '.join(newDesc)

In [ ]:
preprocess_SW("old major the old boar on the manor farm calls the animals on the farm for a meeting where he compares the humans to parasites and teaches the animals a revolutionary song beasts of england when major dies two young pigs snowball and napoleon assume command and turn his dream into a philosophy")

'old major old boar manor farm calls animals farm meeting compares humans parasites teaches animals revolutionary song beasts england major dies two young pigs snowball napoleon assume command turn dream philosophy'

In [ ]:
df['description w/o SW'] = df['description'].apply(lambda x: preprocess_SW(x))

In [ ]:
df.head()

,id,name,genre,description,description w/o SW
0,620,Animal Farm,"[Roman à clef, Satire, Children's literature, ...",old major the old boar on the manor farm calls...,old major old boar manor farm calls animals fa...
1,843,A Clockwork Orange,"[Science Fiction, Novella, Speculative fiction...",alex a teenager living in near future england ...,alex teenager living near future england leads...
2,986,The Plague,"[Existentialism, Fiction, Absurdist fiction, N...",the text of the plague is divided into five pa...,text plague divided five parts town oran thous...
4,2080,A Fire Upon the Deep,"[Hard science fiction, Science Fiction, Specul...",the novel posits that space around the milky w...,novel posits space around milky way divided co...
5,2152,All Quiet on the Western Front,"[War novel, Roman à clef]",the book tells the story of paul b umer a germ...,book tells story paul b umer german soldier ur...

In [ ]:
setOfgenre

{'Absurdist fiction',
 'Adventure',
 'Adventure novel',
 'Albino bias',
 'Alien invasion',
 'Alternate history',
 'American Gothic Fiction',
 'Anthology',
 'Anthropology',
 'Anti-nuclear',
 'Anti-war',
 'Apocalyptic and post-apocalyptic fiction',
 'Autobiographical comics',
 'Autobiographical novel',
 'Autobiography',
 'Bangsian fantasy',
 'Bildungsroman',
 'Biographical novel',
 'Biography',
 'Biopunk',
 'Bit Lit',
 'Black comedy',
 "Boys' school stories",
 'Business',
 'Cabal',
 'Campus novel',
 'Catastrophic literature',
 'Chick lit',
 "Children's literature",
 'Chivalric romance',
 'Collage',
 'Colonial United States romance',
 'Comedy',
 'Comedy of manners',
 'Comic book',
 'Comic fantasy',
 'Comic novel',
 'Comic science fiction',
 'Comics',
 'Coming of age',
 'Computer Science',
 'Conspiracy',
 'Conspiracy fiction',
 'Contemporary fantasy',
 'Cookbook',
 'Cozy',
 'Creative nonfiction',
 'Crime Fiction',
 'Cyberpunk',
 'Dark fantasy',
 'Detective fiction',
 'Drama',
 'Dying Earth subgenre',
 'Dystopia',
 'Economics',
 'Edisonade',
 'Education',
 'Elizabethan romance',
 'Encyclopedia',
 'English public-school stories',
 'Epic Science Fiction and Fantasy',
 'Epistolary novel',
 'Ergodic literature',
 'Erotica',
 'Essay',
 'Existentialism',
 'Experimental literature',
 'Fable',
 'Fairy tale',
 'Fairytale fantasy',
 'Fantastique',
 'Fantasy',
 'Fantasy of manners',
 'Farce',
 'Feminist science fiction',
 'Fiction',
 'Fictional crossover',
 'Field guide',
 'First-person narrative',
 'Foreign legion',
 'Future history',
 'Gamebook',
 'Gay Themed',
 'Gay novel',
 'Georgian romance',
 'Ghost story',
 'Gothic fiction',
 'Graphic novel',
 'Hard science fiction',
 'Hardboiled',
 'Heroic fantasy',
 'High fantasy',
 'Historical fantasy',
 'Historical fiction',
 'Historical novel',
 'Historical romance',
 'Historical whodunnit',
 'History',
 'Horror',
 'Human extinction',
 'Humour',
 'Indian chick lit',
 'Industrial novel',
 'Inspirational',
 'Invasion literature',
 'Juvenile fantasy',
 'Künstlerroman',
 'LGBT literature',
 'Light novel',
 'Literary criticism',
 'Literary fiction',
 'Literary realism',
 'Literary theory',
 'Locked room mystery',
 'Lost World',
 'Low fantasy',
 'Magic realism',
 'Marketing',
 'Mashup',
 'Mathematics',
 'Medieval romance',
 'Memoir',
 'Metaphysics',
 'Military history',
 'Military science fiction',
 'Modernism',
 'Morality play',
 'Music',
 'Mystery',
 'Nature',
 'Naval adventure',
 'Neuroscience',
 'New Weird',
 'New York Times Best Seller list',
 'Non-fiction',
 'Non-fiction novel',
 'Novel',
 'Novella',
 'Parallel novel',
 'Paranormal romance',
 'Parody',
 'Pastiche',
 'Personal journal',
 'Philosophy',
 'Photography',
 'Picaresque novel',
 'Picture book',
 'Planetary romance',
 'Play',
 'Poetry',
 'Polemic',
 'Police procedural',
 'Political philosophy',
 'Politics',
 'Popular culture',
 'Popular science',
 'Pornography',
 'Post-holocaust',
 'Postcyberpunk',
 'Postmodernism',
 'Prose',
 'Prose poetry',
 'Psychological novel',
 'Psychology',
 'Reference',
 'Regency romance',
 'Religion',
 'Religious text',
 'Robinsonade',
 'Role-playing game',
 'Roman à clef',
 'Romance novel',
 'Romantic comedy',
 'Satire',
 'School story',
 'Science',
 'Science Fiction',
 'Science fantasy',
 'Scientific romance',
 'Sea story',
 'Self-help',
 'Serial',
 'Short story',
 'Social commentary',
 'Social criticism',
 'Social novel',
 'Social science fiction',
 'Social sciences',
 'Sociology',
 'Soft science fiction',
 'Space opera',
 'Space western',
 'Speculative fiction',
 'Spirituality',
 'Sports',
 'Spy fiction',
 'Steampunk',
 'Subterranean fiction',
 'Superhero fiction',
 'Supernatural',
 'Suspense',
 'Sword and planet',
 'Sword and sorcery',
 'Techno-thriller',
 'Thriller',
 'Time travel',
 'Tragicomedy',
 'Transgender and transsexual fiction',
 'Transhumanism',
 'Travel',
 'Travel literature',
 'Treatise',
 'True crime',
 'Urban fantasy',
 'Urban fiction',
 'Utopian and dystopian fiction',
 'Utopian fiction',
 'Vampire fiction',
 'War novel',
 'Western',
 'Western fiction',
 'Whodunit',
 'Wuxia',
 'Young adult literature',
 'Youth',
 'Zombie',
 'Zombies in popular culture'}

Grouping similar genres

In [ ]:
book_genres = setOfgenre

In [ ]:
len(book_genres)

227

In [ ]:
from nltk.corpus import stopwords 
import regex as re
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('words')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
def preprocess_genres(i):
    t = stopwords.words("english")
    pattern = re.compile(r'\b(' + r'|'.join(t) + r')\b\s*')
    tokens = nltk.word_tokenize(i)
    s = ""
    s = ", ".join(tokens)
    stopword_removed =[]    
    for word in tokens:
      word = pattern.sub('', word)
      if(len(word)> 0):
        stopword_removed.append(word)
    final_genre = ''  
    for word in stopword_removed:
      final_genre += (word+' ')  
    final_genre = final_genre.strip()  
    return final_genre

In [ ]:
temp_genre = []
for i in df['genre']:
  temp_genre2 = []
  for j in i:
    temp_genre2.append(preprocess_genres(j))
  temp_genre.append(temp_genre2)
df['m-genre'] = temp_genre
df

,id,name,genre,description,description w/o SW,m-genre
0,620,Animal Farm,"[Roman à clef, Satire, Children's literature, ...",old major the old boar on the manor farm calls...,old major old boar manor farm calls animals fa...,"[Roman à clef, Satire, Children ' literature, ..."
1,843,A Clockwork Orange,"[Science Fiction, Novella, Speculative fiction...",alex a teenager living in near future england ...,alex teenager living near future england leads...,"[Science Fiction, Novella, Speculative fiction..."
2,986,The Plague,"[Existentialism, Fiction, Absurdist fiction, N...",the text of the plague is divided into five pa...,text plague divided five parts town oran thous...,"[Existentialism, Fiction, Absurdist fiction, N..."
4,2080,A Fire Upon the Deep,"[Hard science fiction, Science Fiction, Specul...",the novel posits that space around the milky w...,novel posits space around milky way divided co...,"[Hard science fiction, Science Fiction, Specul..."
5,2152,All Quiet on the Western Front,"[War novel, Roman à clef]",the book tells the story of paul b umer a germ...,book tells story paul b umer german soldier ur...,"[War novel, Roman à clef]"
...,...,...,...,...,...,...
16549,36372465,The Third Lynx,[Science Fiction],the story starts with former government agent ...,story starts former government agent frank com...,[Science Fiction]
16551,36534061,Remote Control,"[Thriller, Fiction, Suspense]",the series follows the character of nick stone...,series follows character nick stone ex militar...,"[Thriller, Fiction, Suspense]"
16555,37054020,Transfer of Power,"[Thriller, Fiction]",the reader first meets rapp while he is doing ...,reader first meets rapp covert operation iran ...,"[Thriller, Fiction]"
16556,37122323,Decoded,[Autobiography],the book follows very rough chronological orde...,book follows rough chronological order switchi...,[Autobiography]
16558,37159503,Poor Folk,"[Epistolary novel, Speculative fiction]",makar devushkin and varvara dobroselova are se...,makar devushkin varvara dobroselova second cou...,"[Epistolary novel, Speculative fiction]"

In [ ]:
temp_genre = []
for i in df['m-genre']:
  temp_genre2 = i
  for j in i:
    if (j ==  'Bangsian fantasy'):
      temp_genre2.remove('Bangsian fantasy')   #related to afterlife book
      temp_genre2.append('Afterlife fantasy')
    elif (j ==  'Biopunk'):
      temp_genre2.remove('Biopunk')
      temp_genre2.append('Biotechnology fiction')  #related to biotech fiction
    elif (j ==  'Edisonade'):
      temp_genre2.remove('Edisonade')  #related to great inventor, engineer
      temp_genre2.append('Inventor fiction')  
    elif (j == 'Elizabethan romance'):
      temp_genre2.remove('Elizabethan romance')
    elif (j == 'Ergodic literature'):
      temp_genre2.remove('Ergodic literature')
    elif (j == 'Humour'):
      temp_genre2.remove('Humour')     
      temp_genre2.append('Humor')
    elif (j == 'Künstlerroman'):
      temp_genre2.remove('Künstlerroman') 
    elif (j == 'Postcyberpunk'):
      temp_genre2.remove('Postcyberpunk')     
      temp_genre2.append('cyberpunk')  
    elif (j == 'Robinsonade'):
      temp_genre2.remove('Robinsonade')
  temp_genre.append(temp_genre2)
df['m-genre'] = temp_genre
df

,id,name,genre,description,description w/o SW,m-genre
0,620,Animal Farm,"[Roman à clef, Satire, Children's literature, ...",old major the old boar on the manor farm calls...,old major old boar manor farm calls animals fa...,"[Roman à clef, Satire, Children ' literature, ..."
1,843,A Clockwork Orange,"[Science Fiction, Novella, Speculative fiction...",alex a teenager living in near future england ...,alex teenager living near future england leads...,"[Science Fiction, Novella, Speculative fiction..."
2,986,The Plague,"[Existentialism, Fiction, Absurdist fiction, N...",the text of the plague is divided into five pa...,text plague divided five parts town oran thous...,"[Existentialism, Fiction, Absurdist fiction, N..."
4,2080,A Fire Upon the Deep,"[Hard science fiction, Science Fiction, Specul...",the novel posits that space around the milky w...,novel posits space around milky way divided co...,"[Hard science fiction, Science Fiction, Specul..."
5,2152,All Quiet on the Western Front,"[War novel, Roman à clef]",the book tells the story of paul b umer a germ...,book tells story paul b umer german soldier ur...,"[War novel, Roman à clef]"
...,...,...,...,...,...,...
16549,36372465,The Third Lynx,[Science Fiction],the story starts with former government agent ...,story starts former government agent frank com...,[Science Fiction]
16551,36534061,Remote Control,"[Thriller, Fiction, Suspense]",the series follows the character of nick stone...,series follows character nick stone ex militar...,"[Thriller, Fiction, Suspense]"
16555,37054020,Transfer of Power,"[Thriller, Fiction]",the reader first meets rapp while he is doing ...,reader first meets rapp covert operation iran ...,"[Thriller, Fiction]"
16556,37122323,Decoded,[Autobiography],the book follows very rough chronological orde...,book follows rough chronological order switchi...,[Autobiography]
16558,37159503,Poor Folk,"[Epistolary novel, Speculative fiction]",makar devushkin and varvara dobroselova are se...,makar devushkin varvara dobroselova second cou...,"[Epistolary novel, Speculative fiction]"

In [ ]:
setOfgenre = sum(df['m-genre'],[])
setOfgenre = set(setOfgenre)

In [ ]:
len(setOfgenre)

223

In [ ]:
bk = list(setOfgenre)

In [ ]:
genre_vectors = []

#main_genres = ['Fiction','Comedy','Adventure', 'Non-fiction', 'Romance', 'Mystery', 'Science Fiction', 'Fantasy', 'Horror', 'Historical Fiction', 'Young Adult', 'Spirituality']
main_genres = ['History', 'Poetry', 'Autobiography', 'Romance','Biography', 'Literary', 'Spirituality', 'Western fiction', 'Comedy', 'Adventure',
               'Dark', 'Sociology', 'Comic', 'Anthology', 'Drama', 'Thriller', 'Action',  'Conspiracy', 'Catastrophic', 
               'Young adult','Fantasy', 'Travel', 'Science', 'Speculative', 'Horror', 'Mystery', 'Non fiction']
for genre in bk:
    genre = genre.replace('-', ' ')
    genre = genre.replace('\'', ' ')
    #genre = genre.replace('edisonade', 'inventor')
    tokens = genre.lower().split()
    vector = sum(model[token] for token in tokens) / len(tokens)
    genre_vectors.append(vector)


main_genre_vectors = []
for genre in main_genres:
    genre = genre.replace('-', ' ')
    tokens = genre.lower().split()
    vector = sum(model[token] for token in tokens) / len(tokens)
    main_genre_vectors.append(vector)

In [ ]:
book_genre_df = pd.DataFrame()
book_genre_df['genre'] = bk

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
u_genre_list = []
for j in range(0,223):
  similarity_list = []
  map_j_list = []
  for i in range(len(main_genre_vectors)):
    similarity = cosine_similarity([genre_vectors[j]], [main_genre_vectors[i]])[0][0]
    similarity_list.append(similarity)
    map_j_list.append(i)
  idx = similarity_list.index(sorted(similarity_list)[-1])
  u_genre_list.append(main_genres[idx])

book_genre_df['m-genre'] = u_genre_list

In [ ]:
book_genre_df

                      genre          m-genre
0                   History          History
1           Social sciences          Science
2             Postmodernism         Literary
3              Sword planet        Adventure
4          Social criticism        Sociology
..                      ...              ...
218      Paranormal romance          Romance
219     Fictional crossover  Western fiction
220                  Comedy           Comedy
221  First-person narrative      Non fiction
222               Modernism         Literary

[223 rows x 2 columns]

In [ ]:
temp_genre = []
for i in df['m-genre']:
  temp_genre2 = []
  for j in i:
    mapped_genre = book_genre_df[book_genre_df['genre']==j]['m-genre'].values[0]
    temp_genre2.append(mapped_genre)
  temp_genre.append(temp_genre2)
df['m-genre'] = temp_genre
df

,id,name,genre,description,description w/o SW,m-genre
0,620,Animal Farm,"[Roman à clef, Satire, Children's literature, ...",old major the old boar on the manor farm calls...,old major old boar manor farm calls animals fa...,"[Literary, Comedy, Poetry, Speculative, Non fi..."
1,843,A Clockwork Orange,"[Science Fiction, Novella, Speculative fiction...",alex a teenager living in near future england ...,alex teenager living near future england leads...,"[Science, Anthology, Speculative, Western fict..."
2,986,The Plague,"[Existentialism, Fiction, Absurdist fiction, N...",the text of the plague is divided into five pa...,text plague divided five parts town oran thous...,"[Spirituality, Non fiction, Western fiction, A..."
4,2080,A Fire Upon the Deep,"[Hard science fiction, Science Fiction, Specul...",the novel posits that space around the milky w...,novel posits space around milky way divided co...,"[Science, Science, Speculative, Fantasy, Non f..."
5,2152,All Quiet on the Western Front,"[War novel, Roman à clef]",the book tells the story of paul b umer a germ...,book tells story paul b umer german soldier ur...,"[Western fiction, Literary]"
...,...,...,...,...,...,...
16549,36372465,The Third Lynx,[Science Fiction],the story starts with former government agent ...,story starts former government agent frank com...,[Science]
16551,36534061,Remote Control,"[Thriller, Fiction, Suspense]",the series follows the character of nick stone...,series follows character nick stone ex militar...,"[Thriller, Non fiction, Drama]"
16555,37054020,Transfer of Power,"[Thriller, Fiction]",the reader first meets rapp while he is doing ...,reader first meets rapp covert operation iran ...,"[Thriller, Non fiction]"
16556,37122323,Decoded,[Autobiography],the book follows very rough chronological orde...,book follows rough chronological order switchi...,[Autobiography]
16558,37159503,Poor Folk,"[Epistolary novel, Speculative fiction]",makar devushkin and varvara dobroselova are se...,makar devushkin varvara dobroselova second cou...,"[Literary, Speculative]"

### Step 5: Getting top 5 books from mapped book genre

In [ ]:
for i in test_files:
  print(i[56:])

BAARISHEIN-_Studio_-Anuv-Jain.opus
Kehna-Hi-Kya-_-Bombay-_-Sanah-Moidutty.opus
Matkar-Maya-Ko-Ahankar-_Audio_-By-Neeraj-Arya_s-Kabir-Cafe-From-Album-Panchrang.opus
Mero-Mann-Lagyo-Vrindavan-Mein-_-Krishna-Bhajan-Maanya-Arora-_-Latest-Bhajan-2023.opus
PATWARI-2-_-New-Garhwali-Song-2023-_-Rohit-Chauhan-_-Raj-Tiger-New-Gadwali-Song-2023.opus
Pawan-Singh-_-अंखिया-मिलाओ-_-Palak-Muchhal-_-Ankhiya-Milao-_-Madhu-Sharma-_-New-Bhojpuri-Song-2022.opus
RadhaKrishn-_-Samay-Samjhayega-_-Surya-Raj-Kamal-_.opus
Ranjha-Lyric-Video-Shershaah-Sid.opus
Soulful-Ghazal-Hariharan-Live-at.opus
Abhijeet Srivastava - Chashni (From Bharat).opus
Abida Parveen - Aaqa - Coke Studio Season 9.opus
Akhil - Duniyaa.opus
Bohemia - Lak Da Hulara.opus
Guru Randhawa - Lahore - Remix(Remix By Dj Shadow Dubai).opus
SalimSulaiman - Saaiyaan.opus
Sidhu Moose Wala - Boss.opus
Apna-Time-Aayega-Gully-Boy-Ranveer-Singh-_-Alia-Bhatt-DIVINE-Dub-Sharma-Zoya-Akhtar.opus

In [ ]:
import random
for i in range(len(y_pred)):
  label = y_pred[i]
  j = dct[label][0]
  for m in range(len(j)):
    print("\n")
    print(j[m])
    ans = []
    for k in range(len(df)):
      # print(df['grouped-genre'].iloc[k])
      if j[m] == 'Poetry':
        if j[m] in df['genre'].iloc[k]:
          if 'Romance' in df['m-genre'].iloc[k]:
            # print(df['name'].iloc[k])
            ans.append(df['name'].iloc[k])
      elif j[m] in df['m-genre'].iloc[k]:
        # print(df['name'].iloc[k])
        ans.append(df['name'].iloc[k])
    if(len(ans)!=0):
      print(y_pred[i])
      if(len(ans)>5):
        print(random.sample(ans, 5))
      else:
        print(ans)

Western fiction
4
['Jungle Tales of Tarzan', 'The Boy Who Dared', 'The Pentagon Spy', 'The Golden Spiders', 'Pirate Latitudes']


Spirituality
4
['The Open Society and Its Enemies', 'The Sacrament of the Body and Blood of Christ—Against the Fanatics', 'After Many a Summer', 'Exodus', 'Demons of Chitrakut']


Comedy
4
['Hello Sailor', 'Whisky Galore!', 'Orlovi Rano Lete', "The Falcon's Malteser", 'Company']


Adventure
4
["Mam'zelle Guillotine", 'Arqtiq', 'Infernal Devices: A Mad Victorian Fantasy', 'The Call of the Wild', 'Five Are Together Again']


Romance
4
['Last Sacrifice', "Candide, ou l'Optimisme", "Captain Corelli's Mandolin", 'The Loveday Trials', 'Summer Crossing']


Western fiction
1
['Barchester Towers', 'The Werewolf of Paris', 'The Problem of the Old Gristmill', 'In the Lake of the Woods', 'Last Evenings on Earth']


Romance
1
['The Grand Sophy', 'The House of the Spirits', 'Undead and Unfinished', 'The Corinthian', 'Royal Escape']


Anthology
1
['The Abortion: An Historical Romance 1966', 'A Thousand Splendid Suns', 'High Citadel', "Hell's Half Acre", "Thursday's Child"]


Literary
1
['The Killer Angels: A Novel of the Civil War', 'The Thieves of Ostia', 'The Man Within', 'The Prophet from Ephesus', 'A Sheaf of Bluebells']


Poetry
1
['Love-Letters Between a Nobleman and His Sister']


Romance
5
['Beautiful Creatures', 'Sex and the Single Ghost', 'Amelia', 'Dragonfly in Amber', 'Armadale']


Western fiction
5
['The Generals', 'Conan the Usurper', 'The Roving Party', 'A Civil Contract', 'Gates of Paradise']


Literary
5
['The Black Rose', 'These Three Remain', 'Weep Not, Child', 'The Clan of the Cave Bear', 'Andersonville']


Spirituality
5
['The Sacrament of the Body and Blood of Christ—Against the Fanatics', 'The Stranger', "The Clerk's Prologue and Tale", 'The Great Divorce', 'Walden']


Poetry
5
['Love-Letters Between a Nobleman and His Sister']


Comedy
2
['Eyes of the Storm', "Blart: The Boy Who Didn't Want to Save the World", 'Chart Throb', "L'Épreuve", 'Emma']


Literary
2
['The Unknown Shore', 'The Line of Beauty', 'An Instance of the Fingerpost', 'Heart of Darkness', 'The Gates of Rome']


Western fiction
2
['Abraham Lincoln, Vampire Hunter', 'A Gypsy Good Time', 'The Wailing Siren Mystery', 'Eyes of the Emperor', 'Walk Through Darkness']


Spirituality
2
['A History of God', 'All About Love: New Visions', 'Assassins', 'The Doors of Perception', 'The Wednesday Wars']


Poetry
2
['Love-Letters Between a Nobleman and His Sister']


Comedy
2
['Little Green Men: A Novel', 'The Loved One', 'Manalive', 'JPod', 'Chart Throb']


Literary
2
['The Riddle of the Sands', 'The Walking Drum', 'The House with the Green Shutters', 'Assassin', 'Owls to Athens']


Western fiction
2
['Pride of Carthage', 'Venus in Copper', 'The Black Book', 'Blood Red, Snow White', 'Extremes']


Spirituality
2
['Honus & Me', 'The Wednesday Wars', 'Under Western Eyes', 'The Screwtape Letters', 'King of Ayodhya']


Poetry
2
['Love-Letters Between a Nobleman and His Sister']


Comedy
2
['The Little Golden Calf', 'Florence of Arabia', 'Election', 'London Fields', 'The Nose From Jupiter']


Literary
2
['The Romantics', 'The Pirate', 'East Is East', 'A Hazard of New Fortunes', 'Let the Circle Be Unbroken']


Western fiction
2
['The Penultimate Peril', 'Katherine', 'Vortex', 'Flashman and the Tiger', 'The Fortune of War']


Spirituality
2
['2150 AD', 'Socratic Puzzles', 'Maniac Magee', 'Nausea', 'Twilight']


Poetry
2
['Love-Letters Between a Nobleman and His Sister']


Western fiction
1
['Seeing is Believing', 'Animal World', 'The Way West', 'Lasher', 'The Clue of the Hissing Serpent']


Romance
1
['Freaks: Alive on the Inside', 'Like Water for Chocolate: A Novel in Monthly Installments with Recipes, Romances and Home Remedies', 'Heaven Has No Favorites', 'Blood Promise', 'Persuasion']


Anthology
1
['The Cave', '1876', 'The Two Deaths of Quincas Wateryell', 'The Easter Parade', 'Careful, He Might Hear You']


Literary
1
['The Loveday Honour', "The Armourer's House", 'The Devil Wears Prada', 'The God of Animals', 'The Unquiet Earth']


Poetry
1
['Love-Letters Between a Nobleman and His Sister']


Western fiction
4
['The Masked Monkey', 'Conan', 'The Monkey and the Tiger', 'Partisans', 'Three Witnesses']


Spirituality
4
['Night on the Galactic Railroad', "Darwin's Dangerous Idea", 'Flipped', 'Chuang Tse and the first emperor', "The Clerk's Prologue and Tale"]


Comedy
4
['Strata', 'Penrod Jashber', 'I Capture the Castle', 'The Screwtape Letters', 'House of Leaves']


Adventure
4
['Beware The Fish!', "Smith's Gazelle", "Pandora's Curse", 'Sword Quest', 'Winter Holiday']


Romance
4
['Home of the Gentry', 'O Terceiro Travesseiro', 'Women in Love', 'Sea Glass', 'Joseph Andrews']


Western fiction
1
['The Wanting Seed', 'Sprig Muslin', 'Pilgermann', 'The Unknown Soldier', 'The Garden of the Finzi-Continis']


Romance
1
['Random Acts of Heroic Love', 'The Adventures of Harry Richmond', 'Swamplandia!', 'A Room with a View', 'Wings']


Anthology
1
['To Play the Fool', "He Wouldn't Kill Patience", 'Tough Love', 'Sister of the Bride', 'The End of the Affair']


Literary
1
['I, the Supreme', 'Jonathan Strange & Mr Norrell', "Flashman's Lady", 'Katherine', 'The Gods of War']


Poetry
1
['Love-Letters Between a Nobleman and His Sister']


Western fiction
4
['Visitors from London', 'Death Turns the Tables', 'Not Quite Dead Enough', 'Living Dead in Dallas', 'The Treasure of the Sierra Madre']


Spirituality
4
['Walden', 'Laws', 'The Doors of Perception', 'Utilitarianism', 'Genesis']


Comedy
4
['Choke', 'The Good Soldier Švejk', 'Adventures of Wim', "Gulliver's Travels", 'To Say Nothing of the Dog']


Adventure
4
['Men of Iron', 'Tom Swift Among the Diamond Makers', 'The Poseidon Adventure', 'Atlantis Found', 'Here Lies Arthur']


Romance
4
['Scarlett', 'Absent in the Spring', 'The Food of the Gods and How It Came to Earth', 'Mauprat', 'Ethan Frome']


Romance
5
['Inkheart', 'The Food of the Gods and How It Came to Earth', 'The Woman Who Did', 'Shadow Fires', 'On the Eve']


Western fiction
5
['When Red Is Black', 'The High Window', 'The Glory', 'Affinity', 'The Children of Men']


Literary
5
['Azincourt', 'The Liar', 'Crispin: At the Edge of the World', 'The Thieves of Ostia', 'Knight Crusader']


Spirituality
5
['Night on the Galactic Railroad', 'The Myth of Sisyphus', 'Chuang Tse and the first emperor', "Darwin's Dangerous Idea", 'Jackie & Me']


Poetry
5
['Love-Letters Between a Nobleman and His Sister']


Western fiction
4
['The Kalahari Typing School for Men', 'The Maltese Falcon', 'Breakheart Pass', 'The Exeter Blitz', 'Lee and Grant at Appomattox']


Spirituality
4
['Destiny of Souls', 'Critique of Dialectical Reason', 'The Life You Can Save', 'A History of God', 'All About Love: New Visions']


Comedy
4
['As Seen on TV', 'Sam the Sudden', 'To Venus in Five Seconds', 'Chart Throb', 'England, Their England']


Adventure
4
['Tom Swift and His Giant Cannon', 'The Reptile Room', 'Tom Swift and His Aerial Warship', 'Tom Swift Among the Diamond Makers', 'Beyond the Grave']


Romance
4
['Micah', 'Swimming Without a Net', 'Lady Susan', "The Emperor's Children", "You Don't Know Me"]


Sociology
0
['The Master and His Emissary', 'Two Old Women', 'Fathers and Sons', 'The Naked Ape', 'Straight and Crooked Thinking']


Young adult
0
['Boot Camp', 'Click Here :', 'The Education of Robert Nifkin', 'Sand Monkeys', 'Sons of Destiny']


Comic
0
['Moo', 'Eyes of the Storm', 'Captain Underpants and the Invasion of the Incredibly Naughty Cafeteria Ladies from Outer Space', 'Cause Celeb', 'Something Borrowed']


Comedy
0
['Turbulent Priests', 'The Horse With My Name', 'M*A*S*H: A Novel About Three Army Doctors', 'Backwards', 'House of Leaves']


Poetry
0
['Love-Letters Between a Nobleman and His Sister']


Sociology
0
['The Flivver King', 'End the Fed', 'The Hero with a Thousand Faces', "Hunger's Rogues", 'The Rise and Fall of the Great Powers']


Young adult
0
['Summerland', "It's Not the End of the World", 'A Cage of Butterflies', 'Marked', 'The King of Attolia']


Comic
0
['The Keep', 'Superfudge', 'Mike', 'Freddy and the Ignormus', 'Kiss of the Spider Woman']


Comedy
0
["Don't Go Near the Water", 'The House That Berry Built', 'The Ruling Class', 'The Loved One', 'Sir Nobonk and the Terrible Dreadful Awful Naughty Nasty Dragon']


Poetry
0
['Love-Letters Between a Nobleman and His Sister']


Western fiction
4
["’Salem's Lot", 'A Question of Blood: An Inspector Rebus Novel', 'Uncle Silas', 'The Broken Anchor', 'The Strange Adventures of Rangergirl']


Spirituality
4
['Utilitarianism', 'The Wednesday Wars', 'After Many a Summer', 'The Outsider', 'A Happy Death']


Comedy
4
['The History of Mr. Polly', 'As Comadres', 'JPod', "Candide, ou l'Optimisme", 'Nightmare Abbey']


Adventure
4
['The End', 'Tom Swift and His Giant Cannon', 'Bitten', 'The Sea-Wolf', 'Zoobreak']


Romance
4
['The Kreutzer Sonata', 'An Assembly Such as This', 'The Black Arrow: A Tale of the Two Roses', 'Marked', 'Undead and Unappreciated']


Sociology
0
['Life Against Death: The Psychoanalytic Meaning of History', 'He Knew He Was Right', "Hunger's Rogues", 'Currency Wars', 'The Hero with a Thousand Faces']


Young adult
0
['Web of Dreams', 'Illusions', 'Abarat: Days of Magic, Nights of War', 'Grim Tuesday', 'The Ruby in the Smoke']


Comic
0
['Ring for Jeeves', 'Chart Throb', 'Red Dwarf: Infinity Welcomes Careful Drivers', "The Hitchhiker's Guide to the Galaxy", 'Something Borrowed']


Comedy
0
['Black Cocktail', 'The Sirens of Titan', 'Treasure Hunters', 'Sam the Sudden', 'The New Paul and Virginia']


Poetry
0
['Love-Letters Between a Nobleman and His Sister']


Sociology
0
['Diary of a Drug Fiend', 'Thérèse Raquin', 'Exit, Voice, and Loyalty', 'Bring Home the Revolution', 'The War Within: A Secret White House History']


Young adult
0
["Thursday's Child", 'Tom Swift and His Wizard Camera', 'Storm Thief', 'Disappearance', 'Reef of Death']


Comic
0
['Matilda', 'Lies and the Lying Liars Who Tell Them', 'Captain Underpants and the Invasion of the Incredibly Naughty Cafeteria Ladies from Outer Space', 'You Suck: A Love Story', "Breathers: A Zombie's Lament"]


Comedy
0
['A Melon for Ecstasy', 'No Way to Treat a First Lady', 'The Ruling Class', 'Service With a Smile', 'Enderby Outside']


Poetry
0
['Love-Letters Between a Nobleman and His Sister']

# Book to Book

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

Encoding multiple labels since each data point can belong to multiple classes

In [ ]:
mBin = MultiLabelBinarizer()

In [ ]:
mBin.fit(df['m-genre'])

MultiLabelBinarizer()

In [ ]:
label = mBin.transform(df['m-genre'])

Splitting into training and testing data

In [ ]:
trainData, testData, trainLabel, testLabel = train_test_split(df['description w/o SW'],label, random_state=0, train_size = .80)

Converting the input text to feature vectors

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=10000)
trainData_v = tfidf_vectorizer.fit_transform(trainData)
testData_v = tfidf_vectorizer.transform(testData)

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
lr = LogisticRegression()
clf = OneVsRestClassifier(lr)
clf.fit(trainData_v, trainLabel)

OneVsRestClassifier(estimator=LogisticRegression())

In [ ]:
from sklearn.metrics import f1_score, accuracy_score

In [ ]:
y_pred = clf.predict(testData_v)
f1_score(testLabel, y_pred, average="micro"), accuracy_score(testLabel, y_pred)

(0.42473974280465404, 0.11716621253405994)

In [ ]:
def predict(m):
    m = updateDescription(m)
    m = preprocess_SW(m)
    m_vec = tfidf_vectorizer.transform([m])
    m_pred = clf.predict(m_vec)
    return mBin.inverse_transform(m_pred)

In [ ]:
test_df = pd.DataFrame(testData)
test_df.head()

                                      description w/o SW
12457  incident saudi arabia touches world war iii un...
1403   british risen power egypt suppress worship old...
6325   year old annabel hope jayquith beautiful famou...
11366  midsomer worthy writers circle group amateur n...
4374   book follows jason worthing also known jazz bo...

In [ ]:
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(testLabel, y_pred)

array([[[2483,    0],
        [  83,    3]],

       [[2016,   44],
        [ 463,   46]],

       [[2520,    0],
        [  49,    0]],

       [[2543,    0],
        [  26,    0]],

       [[2568,    0],
        [   1,    0]],

       [[2525,    0],
        [  44,    0]],

       [[2531,    0],
        [  37,    1]],

       [[2566,    0],
        [   3,    0]],

       [[2564,    0],
        [   5,    0]],

       [[2406,    1],
        [ 150,   12]],

       [[2010,   38],
        [ 267,  254]],

       [[2513,    0],
        [  55,    1]],

       [[2439,    1],
        [ 122,    7]],

       [[2387,    0],
        [ 173,    9]],

       [[2284,    8],
        [ 217,   60]],

       [[1160,  355],
        [ 563,  491]],

       [[2097,   34],
        [ 348,   90]],

       [[2460,    0],
        [ 109,    0]],

       [[1945,   38],
        [ 282,  304]],

       [[2560,    0],
        [   9,    0]],

       [[1524,  174],
        [ 435,  436]],

       [[2553,    0],
        [  16,    0]],

       [[2415,    0],
        [ 153,    1]],

       [[2562,    0],
        [   7,    0]],

       [[2335,    3],
        [ 218,   13]],

       [[2397,    1],
        [ 165,    6]]])

In [ ]:
from sklearn.metrics import hamming_loss
hamming_loss(testLabel,y_pred)

0.07032068748690003

In [ ]:
c = 0
for i in predict(test_df['description w/o SW'][12457]):
  j = set(i)
  for m in range(len(df['m-genre'])):
    n = set(df['m-genre'].iloc[m])
    if len(n.intersection(j)) == len(j):
      if len(n.intersection(j)) == len(n):
        print(df['name'].iloc[m])
        c+=1

print(c)

Lions' Commentary on UNIX 6th Edition, with Source Code
The Number of the Beast
Farnham's Freehold
The Stardroppers
A Descent into the Maelstrom
Long Voyage Back
Niourk
Andromeda
The Man Who Awoke
The Genesis Quest
The Futurological Congress
Children of the Atom
Isaac Asimov's Utopia
On My Way to Paradise
The Metamorphosis of Prime Intellect
Dark Tide: Onslaught
Recovery
Edge of Victory: Conquest
Edge of Victory: Rebirth
The Müller-Fokker Effect
Earthlight
Enemy Lines: Rebel Dream
Force Heretic: Remnant
Force Heretic: Refugee
Force Heretic: Reunion
Red Star
Flatterland
Vril
Magic, Inc.
Tin Woodman
The Lost City of the Jedi
The Soul of a New Machine
The Planiverse
Nightshade
Autumn Visits
Roadside Picnic
Dune: House Atreides
Coyote
Time in Advance
Sutherlin Alliance
Sphereland
Splinter of the Mind's Eye
The Far Arena
The Ties That Bind
The Black Cloud
Saturn Rukh
Galaxy of Fear: Ghost of the Jedi
The Cookie Monster
Inter Ice Age 4
Oms en Série
Far Rainbow
The Kid from Hell
.hack//AI buster
.hack//Another Birth
.hack//Zero
Space Mowgli
The Glove of Darth Vader
Beetle in the Anthill
Star Wars Republic Commando: Hard Contact
The Quiet Game
The Traveler
Night of the Big Heat
The Dream Master
The Land of Crimson Clouds
The Bull's Hour
Razor's Edge
Rocheworld
Colossus
Galax-Arena
The Ghosts of N-Space
Junior Jedi Knights: Lyric's World
Junior Jedi Knights: Promises
Junior Jedi Knights: The Golden Globe
Junior Jedi Knights: Kenobi's Blade
Band of Gypsys
Gravity Dreams
Monument
Evening's Empire
Myron
Hot Sleep
Man After Man: An Anthropology of the Future
Time Jumper
Tool of the Trade
Path of Destruction
Boba Fett: The Fight to Survive
Jedi Apprentice: Deceptions
Ravage
La Nuit des temps
Ceres Storm
Only Human
Wizard of Venus
The Sentimental Agents in the Volyen Empire
Cosmos
No Man Friday
Boba Fett: Crossfire
The Invention of Morel
.hack//AI buster 2
Master of the Void
O-zone
Across The Zodiac
MedStar II: Jedi Healer
Children of the Jedi
Star Wars Galaxies: The Ruins of Dantooine
Meg: Primal Waters
Meg: Hell's Aquarium
The Hive
A Forest Apart
Fool's Bargain
Shadows in Flight
Planet X
The Man Who Would Be Queen
Sister Alice
Star Wars Jedi Quest 8: The Changing of the Guard
The Magellanic Cloud
Mission: Impractical
The Possibility of an Island
Star Wars Jedi Quest 1: The Way of the Apprentice
Devil on My Back
The Last of the Jedi: A Tangled Web
The Last of the Jedi: Dark Warning
The Last of the Jedi: Underworld
The Last of the Jedi: Death on Naboo
Galaxy of Fear: Eaten Alive
Galaxy of Fear: The Nightmare Machine
Galaxy of Fear: Army of Terror
Galaxy of Fear: The Brain Spiders
Galaxy of Fear: The Doomsday Ship
Galaxy of Fear: The Hunger
Zorba the Hutt's Revenge
Mission from Mount Yoda
Queen of the Empire
Prophets of the Dark Side
The Well-Mannered War
Definitely Maybe
Exiles to Glory
The Wild Boy
The Lab
Cloud's Rider
Reality Dust
Exile's Gate
Island of Death
Bullet Time
The Eleventh Tiger
Rags
Fear of the Dark
The Scapegoat
Winner Takes All
The Plotters
Around the Moon
Or Die Trying
The Strange World of Planet X
I am a Dalek
Red Thunder
Last Full Measure
Who He?
The Second Angel
The Story of the Phantom: The Ghost Who Walks
The Adolescence of P-1
The Highway Men
Black Oceans
F.P.1 Doesn't Respond
Dead Boys
Dawkins' God: Genes, Memes, and the Meaning of Life
Der Tunnel
The Answer
For a New Liberty: The Libertarian Manifesto
Things Not Seen
Those Who Walk In Darkness
Dorsai!
The Last of the Jedi: Return of the Dark Side
Saturnalia
Firebird
Icefire
Stopping at Slowyear
A Practical Man
Still Forms on Foxfield
Northworld
Erasing Sherlock
The Last of the Jedi: Secret Weapon
Out of Time’s Abyss
The Doomed City
Ladies Whose Bright Eyes
Pax Britannia: El Sombra
Sun of Suns
The Dawkins Delusion?
The Fur
City on Fire
The Bug Wars
Subspace Encounter
End time
The Well of Stars
The Continent Makers
The Fatal Eggs
Terrarium
Birth of Fire
The Last Day of Creation
Downsiders
Babylon 5: Clark's Law
.hack//CELL
Babylon 5: The Passing of the Techno-Mages - Casting Shadows
Babylon 5: The Passing of the Techno-Mages - Invoking Darkness
Command & Conquer: Tiberium Wars
Est: The Steersman Handbook
In Limbo
Venture to the Moon
Midnighters 2: Touching Darkness
Halo: Contact Harvest
The Starship Trap
Mission to Mercury
Spaceship to Saturn
The Mohole Mystery
Nearly Neptune
First Contact?
Passage to Pluto
Tony Hale, Space Detective
Murder on Mars
The Caves of Drach
The Last Disaster
The Dark Triangle
It's Superman
The Shield of Achilles: War, Peace, and the Course of History
A Scourge of Screamers
The Last Children of Schewenborn
Sten Adventures Book 5: Revenge of the Damned
With Folded Hands
Vulcan's Glory
Ilium/Olympus
The Last of the Jedi: Against the Empire
Parallel Worlds
The Marvelous Effect
Gray Matters
Paprika
Mahars of Pellucidar
The Angel of the Revolution
Acorna's Search
Shards of Honor
The Legion of Space
The Farther Shore
Thor Meets Captain America
Speech Sounds
Ace in the Hole
Dead Mountaineer's Hotel
Reflex
The Intergalactic Kitchen
The Clone Republic
Pattern for Conquest
Minions of the Moon
Cosmic Engineers
Renaissance
The Starmen
Mel Oliver and Space Rover on Mars
The Forgotten Planet
Star Bridge
Address: Centauri
Sargasso of Space
This Fortress World
Reprieve from Paradise
Plague Ship
Path of Unreason
The Survivors
The Bird of Time
Invaders from the Infinite
The Philosophical Corps
Doom 3: Worlds on Fire
Pursuit of the Screamer
The Forbidden Garden
The Book of Ptath
Sinister Barrier
Skylark of Valeron
Seven Out of Time
Le Vingtième siècle. La vie électrique
The Bridge of Light
The Cometeers
Dreadful Sanctuary
Seeds of Life
The Crystal Horde
Man of Many Minds
Three Thousand Years
Under the Triple Suns
Alien Minds
Islands of Space
The Heads of Cerberus
The Abyss of Wonders
The Time Stream
The Mightiest Machine
The Torch
Lords of Creation
Exiles of Time
Nomad
Out of Gas: The End of the Age of Oil
The World Below
Murder in Millennium VI
The Creator
Behind the Evidence
The Night People
The Sunken World
The Radio Man
Murder Madness
The Rat Race
After 12,000 Years
The Iron Star
Lecture Demonstration
The Planet of Youth
People of the Comet
The Moon Maiden
The Port of Peril
The Goddess of Ganymede
The Bowl of Baal
Spaceship Medic
Echo Round His Bones
To the Stars
Millennium Falcon
Thorns
Land of Terror
Savage Pellucidar
Logan's World
Synthetic Men of Mars
Jumper: Griffin's Story
Gears of War: Aspho Fields
Eva
Relic of Empire
The Lost Fleet: Valiant
The Lost Fleet: Dauntless
The Klingon Gambit
The Covenant of the Crown
The Prometheus Design
The Abode of Life
Black Fire
Triangle
Web of the Romulans
Mutiny on the Enterprise
The Trellisane Confrontation
My Enemy, My Ally
The Tears of the Singers
The Vulcan Academy Murders
Uhura's Song
Shadow Lord
Killing Time
Dwellers in the Crucible
Pawns and Symbols
Prisoner of the Daleks
Crisis on Centaurus
Dreadnought!
Demons
Chain of Attack
Deep Domain
Dreams of the Raven
The IDIC Epidemic
Timetrap
The Three-Minute Universe
Memory Prime
The Final Nexus
Double, Double
The Cry of the Onlies
Rules of Engagement
The Pandora Principle
Doctor's Orders
Enemy Unseen
Home Is the Hunter
The Lost Fleet: Fearless
Dark Mirror
Missile Gap
The Clone Wars
Ghost Walker
A Flag Full of Stars
The Blue World
The Five Gold Bands
From Here to Infinity
Ranks of Bronze
The Forlorn Hope
Son of the Tree
Incandescence
The Planet Savers
The Sword of Aldones
The Bloody Sun
Star of Danger
Flood
Falcons of Narabedla
The Cyborg from Earth
The Door Through Space
Into the Looking Glass
Stranglers' Moon
Oceanic
The World Wreckers
Isaac Asimov's Robot City: Odyssey
Isaac Asimov's Robot City: Suspicion
Isaac Asimov's Robot City: Prodigy
Isaac Asimov's Robot City: Refuge
Isaac Asimov's Robot City: Perihelion
Archform: Beauty
Semper Mars
The World in Winter
The Year of the Angry Rabbit
The Gray Cloth
Quofum
Babylon Babies
Doom 3: Maelstrom
Zanesville
Autonomy
Chroniques du Pays des Mères
The Krillitane Storm
The Visitors
Colossus and the Crab
Homunculus
O Presidente Negro
Fifth Planet
Ossian's Ride
Galactic Odyssey
Thirteenth City
The Last of the Immortals
The Winds of Dune
Headlong
March Upcountry
Betrayal
Star Wars: Darth Bane: Dynasty of Evil
Shangri-La
Torch of Freedom
Mission of Honor
The Master: An Adventure Story
Genesis
God Drug
Marooned on Mars
The Lost Fleet: Relentless
Computer One
The Death Guard
The Inferior
Wagon Train to the Stars
Belle Terre
Rough Trails
The Flaming Arrow
Thin Air
Final Draft
Abyss
Rogue
The Honour of the Knights
Mindplayers
March to the Sea
March to the Stars
By Heresies Distressed
Hidden Empire
Rollback
Daniel X: Watch the Skies
Death Troopers
The Romulan War: Beneath the Raptor's Wing
Kobayashi Maru
The Good That Men Do
Broken Bow
Shockwave
What Price Honor?
Surak's Soul
The Expanse
Daedalus
Daedalus's Children
Rosetta
Wyst: Alastor 1716
Competitors
The Depths of Time
The Wizard of Linn
High Vacuum
Timeliner
Mach 1: A Story of Planet Ionus
The Unincorporated Man
The Quiet War
Barbary
Star Wars: Crosscurrent
One in Three Hundred
All You Need Is Kill
Snow White and the Giants
The Monster Men
Transit
A Mighty Fortress
The Evolutionary Void
The Sunless City
The Dead Father
Star Wars Imperial Commando: 501st
Ballroom of the Skies
Metal Fatigue
The Star-Crowned Kings
Mass Effect: Retribution
Keeping It Real
The Lost Fleet: Victorious
There Will Be Time
Wonders of a Godless World
Santa Olivia
Dominant Species
Palos of the Dog Star Pack
The Mouthpiece of Zitu
Jason, Son of Jason
Shadrach in the Furnace
Maza of the Moon
Cryoburn
Gears of War: Anvil Gate
Abercrombie Station
Dragonheart
Eternity Road
Phule's Company
Stone Spring
Phule's Paradise
Daniel X: Demons and Druids
The Grand Design
Medusa: A Tiger by the Tail
Embassytown
Zendegi
Surface Detail
Greybeard
Conjure Wife
The Coming of the Terraphiles
With the Lightnings
Dead Space: Martyr
Deeper
Buddy Holly is Alive and Well on Ganymede
The Quantum Thief
Exodus
Orion in the Dying Time
The Man in the Moone
Vengeance of Orion
The Carbon Diaries: 2015
The Apocalypse Troll
.hack//Epitaph of Twilight
Lurulu
Night Lamp
The Rising
The Privateer
The Independent Command
Memory
Hellhole
The Outlaws of Mars
We Who Are About To...
The Maker of Universes
Beyond the Frontier: Dreadnaught
The Law of Nations
The Information: A History, a Theory, a Flood
Transformers: Dark of the Moon: The Junior Novel
Berge Meere und Giganten
Robopocalypse
Feed
A Beautiful Friendship
Ready Player One
The Last Space Viking
How Firm a Foundation
Dragon's Time
Dragongirl
Postsingular
Wake
The Lady With the X-Ray Eyes
Bro
A Rising Thunder
Brothers in Arms
The Stories of Ibis
Earth Unaware
The Twilight of Briareus
The Third Lynx
552

In [ ]:
for i in test_df.index[0:15]:
  print(i)
  print("Predicted: ", predict(test_df['description w/o SW'][i]))
  print("Actual: ", df['m-genre'][i])
  print("Name: ", df['name'][i])

12457
Predicted:  [('Science',)]
Actual:  ['Western fiction']
Name:  Doomsday Plus Twelve
1403
Predicted:  [('Speculative',)]
Actual:  ['Travel', 'Speculative', 'Fantasy', 'Adventure']
Name:  The Anubis Gates
6325
Predicted:  [('Non fiction',)]
Actual:  ['Mystery', 'Speculative', 'Young adult', 'Romance']
Name:  Forbidden
11366
Predicted:  [()]
Actual:  ['Non fiction']
Name:  Written in Blood
4374
Predicted:  [('Science', 'Speculative')]
Actual:  ['Science']
Name:  Hot Sleep
5335
Predicted:  [()]
Actual:  ['Science', 'Speculative', 'Fantasy', 'Non fiction']
Name:  Making Money
7494
Predicted:  [('Mystery', 'Non fiction')]
Actual:  ['Thriller', 'Mystery', 'Science', 'Speculative', 'Non fiction']
Name:  Still Life with Crows
427
Predicted:  [('Non fiction', 'Science')]
Actual:  ['Science', 'Anthology', 'Speculative', 'Western fiction', 'Drama', 'Non fiction']
Name:  On the Beach
14619
Predicted:  [('Mystery',)]
Actual:  ['Mystery']
Name:  The Leper of Saint Giles
10193
Predicted:  [('Non fiction',)]
Actual:  ['Mystery', 'Mystery']
Name:  The Left Leg
608
Predicted:  [()]
Actual:  ['Non fiction']
Name:  Tell England
7102
Predicted:  [()]
Actual:  ['Speculative', 'Poetry']
Name:  Molly Moon's Hypnotic Time-Travel Adventure
2585
Predicted:  [()]
Actual:  ['Young adult', 'Anthology']
Name:  Anne's House of Dreams
5129
Predicted:  [('Fantasy', 'Horror', 'Science', 'Speculative')]
Actual:  ['Speculative', 'Horror', 'Poetry']
Name:  Close to the Ground
2810
Predicted:  [('Non fiction', 'Science', 'Speculative')]
Actual:  ['Fantasy', 'Science', 'Anthology', 'Speculative', 'Literary', 'Non fiction']
Name:  Hyperion